Add files via upload

diff --git a/Fast-DL-PIA b/Fast-DL-PIA
--- a/Fast-DL-PIA
+++ b/Fast-DL-PIA
@@ -40,7 +40,7 @@ if command -v wget >/dev/null 2>&1 ; then
 Downloader="wget"
 elif
 command -v curl >/dev/null 2>&1 ; then
-Downloader="curl -O"
+Downloader="curl"
 fi
 
 tput sgr0 # Reset Terminal Colors
@@ -89,16 +89,20 @@ EOF
   read -r -n 1 -p "Would you like to attempt download and install now? [y/n] " response
 tput sgr0 # Reset Terminal Colors
 case "${response}" in
-    [yY]) 
-        "${Downloader}" "${targetDL}"
+    [yY])
+	if [ "${Downloader}" = curl ]; then
+        $(curl -O "${targetDL}")
+	else
+	"${Downloader}" "${targetDL}"
+	fi
         sudo dpkg -i "$(basename "${targetDL}")"
         exec $(readlink -f "$0")
-		;;
+exit		;;
     *)
 		printf "%b\n"
 		exit
         ;;
-esac    
+esac
 fi
 
 
@@ -122,13 +126,26 @@ tput sgr0 # Reset Terminal Colors
 exit
 fi
 clear
+
+# Check for Internet Access with max retries of 3 then print message
 tput cup 5 0
-printf "%b\n" "Checking For Internet Access"
+printf "%b\n" "Checking For Internet Access"; printf "%b\n" "Pinging Google.com"; tput blink; printf "%b\n" ".";tput cup 9 0;tput sgr0 # Reset Terminal Colors
 if ping -q -c 2 -W 1 google.com >/dev/null; then
   clear
-else
+else 
+n=0
+   until [ $n -ge 2 ]
+   do
+      ping -q -c 2 -W 1 google.com >/dev/null 
+      if [ $? -eq 0 ]; then
+        break
+      fi
+      n=$[$n+1]
+
+   done
 clear
-tput cup 5 0
+tput cup 15 0
+printf "%b\n" "Retried 3 Times"
 printf "%b" "Network appears to be down. Unable to reach google.com for network connectivity test" "\n\n"
 exit
 fi
@@ -187,7 +204,7 @@ tput ed # Clear all text below cursor
 read -n 1 option # Wait and read menu selection then continue with a single key press
 
 case "${option}" in
-    1) 
+    1)
         PIA_Menu
         ;;
     2)
@@ -219,7 +236,7 @@ printf "%b" "Checking For PIA's Fastest Server...Please Wait." "\n\n"
 if [ "${selection}" -eq 0 ]; then # Zero from PIA_Menu. All servers PIA has
 tput setaf 3 # Yellow Text
 printf "%b" "Checking All Servers Takes More Time....Be Patient" "\n" # warning that this worldwide server check takes longer
-server=$(wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]') # Gets ALL servers
+server=$(wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]' | uniq) # Gets ALL servers
 serverCount=$(printf "%b\n" "${server}" | wc -l) # Counts the servers being selected
 countries=$(printf "%b\n" "${server}" | cut -c 1-2 | uniq | wc -l) # Counts the countries PIA has servers in
 tput setaf 2 # Green Text
@@ -230,10 +247,14 @@ else
 #------------------------------------------------------------------------------------------------------
 server=$(wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]' | grep "${LOCATION}") # Only check selected country
 serverCount=$(printf "%b\n" "${server}" | wc -l) # Count the servers in selected country
+tput setaf 3 # Green Text
 printf "%b\n" "Checking "${serverCount}" Locations in Selected Country" # Print the number of server locations in selected country
+tput sgr0
 fi
 
+if [ "${selection}" -ne 0 ]; then
 printf "%b\n" "${server}" # Prints the selected server locations
+fi
 # Sudo Check
 #-----------------------------------------------------------------
 tput setaf 1 # Red Text
@@ -247,29 +268,53 @@ printf "%b\n" "${server}" | xargs sudo netselect -s 1 > file1 # Pipes each of th
 tput sgr0 # Reset Terminal Colors
 tput cup 15 0 # Move cursor to line 15 column 0
 tput ed # Delete text below cursor
-printf "%b" "Fastest Hostname" "\n\n"
-tput setaf 1 # Red Text
 fhostname=$(cat file1 | awk '{print $2}') # Save fastest hostname
-printf "%b\n" "${fhostname}"
+printf "%b" "Fastest Hostname ";tput setaf 1; printf "%b" "${fhostname}" "\n"
 printf "%b\n"
 host "${fhostname}" > file2 # Pipe fastest hostname into the command 'host' to find all IP's for hostname'
 IPs=$(cat file2 | awk '{print $4}') # Save IP addresses
 cAddresses=$(wc -l file2 | awk '{print $1}') # Count IP addresses
-printf "%b" "${fhostname}";tput setaf 3;printf "%b" " Has "${cAddresses}" Servers For That Hostname" "\n\n" # Print the number of IP addresses
 tput sgr0
-printf "%b" "Checking For The Fastest IP Address To "${fhostname}" " "\n"
+printf "%b" "Checking For The Fastest IP Address To";tput setaf 2; printf "%b" " "${fhostname}" " "\n\n"
+printf "%b" "${fhostname}";tput setaf 3;printf "%b" " Has "${cAddresses}" Servers For That Hostname" "\n\n" # Print the number of IP addresses
+tput sgr0 # Reset Terminal Colors
 printf "%b\n" "${IPs}" # Print IP addresses
 tput setaf 2 # Green Text
 FinalIP=$(printf "%b\n" "${IPs}" | xargs sudo netselect -s 1 | awk '{print $2}') # Pipe the saved IP's in Netselect and select fastest IP
 tput setaf 3 # Yellow Text
 resptime=$(ping -c 10 "${FinalIP}" | tail -1| awk -F '/' '{print $5 "ms"}') # Save the average ping time of the fastest IP
-tput cup 22 0 # Move cursor to line 22 column 0
+tput cup 20 0 # Move cursor to line 20 column 0
 tput ed # Delete text below cursor
 printf "%b\n"
 printf "%b\n" "${FinalIP}" "Has an Avg Response Time Of "${resptime}"" # Print fastest IP and average ping time
-printf "%b\n\n"
+
 tput sgr0
 rm file1 file2 # remove the temporary files
+
+# restart script after Server check
+
+cat <<"EOF"
+
+Test Complete
+
+Select Option
+
+1. Back To Main Menu
+2. Exit / Quit
+
+EOF
+
+	read -n 1  continue
+	case "${continue}" in
+    1) 
+     Main_Menu
+     ;;
+    *)
+     tput ech 1
+     printf "%b\n"
+     exit
+     ;;
+     esac
 }
 
 PIA_Menu() {
@@ -338,9 +383,9 @@ case "${selection}" in
 	9)
 	LOCATION="israel";;
 	*)
-	clear
-	Banner
-	PIA_Menu
+	#clear
+	#Banner
+	Main_Menu
 	tput cup 14 0
 	tput ed
 	;;
