Add files via upload

diff --git a/PIA b/PIA
--- a/PIA
+++ b/PIA
@@ -13,8 +13,15 @@
 # sudo and apt are used to offer user to install an unmet dependancy that is package installable
 # Outside of package manager Dependency requires manual install
 #curl -s 'https://api.ipify.org'
+#
+#  curl_or_wget=$(if hash curl 2>/dev/null; then echo curl; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi)
+# if [ -z "$curl_or_wget" ]; then
+#    echo "Neither curl nor wget found. Cannot use http method." >&2
+#    exit 1
+#fi
 #----------------------------------------------------------------------------------------------------
-tput smcup
+#tput smcup
+tput sc
 CHECKMARK="$(tput sgr0)[$(tput setaf 2)✔$(tput sgr0)]"
 XMARK="$(tput sgr0)[$(tput setaf 1)X$(tput sgr0)]"
 
@@ -166,11 +173,11 @@ fi
 
 # Check for Internet Access with max retries of 3 then print message
 #clear
-tput cup 0 0 # Move cursor to line 15 column 0
-tput ed # Clear all text below cursor
-tput cup 5 0
+#tput cup 0 0 # Move cursor to line 0 column 0
+#tput ed # Clear all text below cursor
+#tput cup 5 0
 
-printf "%b\n" "Checking For Internet Access"; printf "%b\n" "Pinging Google.com"; tput blink; printf "%b\n" ".";tput cup 9 0;tput sgr0 # Reset Terminal Colors
+printf "%b\n" "Checking For Internet Access"; printf "%b\n" "Pinging Google.com"; tput blink; printf "%b\n" ".";tput cup 0 0;tput sgr0 # Reset Terminal Colors
 tput civis
 if ping -q -c 2 -W 1 google.com >/dev/null; then
     printf "%b\n"
@@ -187,7 +194,7 @@ else
 
     done
 
-    tput cup 0 0 # Move cursor to line 15 column 0
+    tput cup 0 0 # Move cursor to line 0 column 0
     tput ed # Clear all text below cursor
     tput cup 5 0
     printf "%b\n" "Retried 3 Times"
@@ -200,10 +207,11 @@ fi
 
 
 Banner() {
-    tput cup 0 0 # Move cursor to line 15 column 0
-    tput ed # Clear all text below cursor
-    tput setaf 2 # Green Text
-    cat <<"EOF"
+	tput rc
+	tput cup 0 0 # Move cursor to line 15 column 0
+	tput ed # Clear all text below cursor
+	tput setaf 2 # Green Text
+	cat <<"EOF"
 https://github.com/optio50/PIA-Server-Check
 
     ____           _                   _
@@ -235,7 +243,7 @@ Main_Menu() {
     printf "%b\n"
     tput cup 16 0 # Move cursor to line 15 column 0
     tput ed # Clear all text below cursor
-    tput civis
+    tput civis # invisible cursor
     # Begin Print Main Menu Selections
     cat <<"EOF"
 
@@ -252,7 +260,7 @@ Select Option
 EOF
     # End Print Main Menu Selections
 
-    tput cup 26 0 # Move cursor to line 22 column 0
+    tput cup 26 0 # Move cursor to line 26 column 0
     tput ed # Clear all text below cursor
 
     read -r -n 1 option # Wait and read menu selection then continue with a single key press
@@ -278,10 +286,12 @@ EOF
 			LeakTest
 			;;
 		7)
-            tput cup 25 0
-            tput ed
+            #tput cup 25 0
+            #tput ed
             tput cnorm
-            tput rmcup
+            #tput rmcup
+			tput el1
+			printf "%b\n"
             exit
             ;;
         *)
@@ -888,10 +898,11 @@ Location_Check(){
 
             if [[ "${MYIP}" =~ ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$ ]]; then
                 MYIP="${MYIP}"
-            #else
-            #    printf "%b\n" "Unable to print Location Map URL"
-            #    #printf "%b\n" "${MYIP}"
-            #    read -r -n 1 -p " Press Any Key To Continue " continue
+            else
+                printf "%b\n" "Unable to Find Valid Information"
+                #printf "%b\n" "${MYIP}"
+                read -r -n 1 -p " Press Any Key To Continue " continue
+			Main_Menu
             fi
 			#curl -s http://ip-api.com/#"${MYIP}" | sed 's/[",{}]//g'
             #MYIP=$(curl -s "http://ipinfo.io/" | awk -F\" '{print $4}' | head -n2 | tail -n1)
@@ -928,31 +939,53 @@ sure its not a \"Virtual Server\" but real hardware in that area.
 }
 
 LeakTest(){
+
+if hash dig 2>/dev/null; then
+    printf "%b\n"
+
+else
+    
+    tput cup 16 0
+    tput ed
+    tput setaf 1
+    printf "%b\n" "dig is required for dns leak testing but not found"
+    printf "%b\n"
+    tput sgr0
+    printf "%b\n" "Would you like to try and install it with apt?"
+    printf "%b\n"
+
+    read -r -n 1 -p "[y/N] " response
+    case "${response}" in
+        [yY])
+            sudo apt install dnsutils
+            ;;
+        *)
+			
+            Main_Menu
+            ;;
+    esac
+
+fi
+
 	tput cup 16 0
     tput el1
     tput ed
-    printf "%b\n"
-	for run in {1..5}
+    #printf "%b\n"
+printf  "Scanning For DNS Leaks."
+
+	for run in {1..20}
 	do
-printf "%b\n" "Scanning For DNS Leaks."
-tput cup 16 0
-tput el
-tput el1
-tput ed
-ping -W1 -c1 whoami.akamai.net | awk ' /from/{print $4}' | sed 's/[)(]//g' | sed 's/://' >> DNS.txt &
-tput cup 16 0
-tput el
-tput el1
-tput ed
-printf "%b\n" "Scanning For DNS Leaks."
-ping -W1 -c1 whoami.ultradns.net | awk ' /from/{print $4}' | sed 's/[)(]//g' | sed 's/://' >> DNS.txt &
-tput cup 16 0
-tput el
-tput el1
-tput ed
-printf "%b\n" "Scanning For DNS Leaks."
+dig +short txt whoami.ds.akahelp.net | tr -d '[ ] [ns] ["] [ecs] [ip] []' >> DNS.txt
+
+done & SPIN_PID=$!
+
+PBint=.2
+spin
 wait
-done
+disown $SPIN_PID 2> /dev/null
+kill -9 $SPIN_PID 2> /dev/null
+
+sed -i 's/255.255.255.255//g' DNS.txt
 sort < DNS.txt | uniq > uniDNS.txt && mv uniDNS.txt DNS.txt
 while read IP; do
 printf "${IP} " >> DNS2.txt; printf "%b" $(whois "${IP}" | awk '/NetName/ {print $2;exit}') "\n" >> DNS2.txt
@@ -968,7 +1001,9 @@ tput sgr0
 grep -v 'fgets' DNS2.txt | column -t
 rm uniDNS.txt DNS2.txt DNS.txt 2> /dev/null
 printf "%b\n\n"
-            read -r -n 1 -p " Select 1 for Retest or any other Key for Main Menu " selection
+		read -r -n 1 -p " Select 1 for Retest
+            
+Any Other Key For Main Menu " selection
             case "${selection}" in
 		1)
 		LeakTest
